name: Teacher Performance CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-train:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Machine Learning Model
        run: |
          python train.py

      - name: Check Saved Model
        run: |
          ls -R
          test -f models/model.pkl

      - name: Upload Trained Model
        uses: actions/upload-artifact@v4
        with:
          name: teacher-performance-model
          path: models/model.pkl